services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - 9000:9000
    volumes:
      - ./backend:/var/www/html

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - 8888:8888
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - backend
